# Generated by Django 5.1.6 on 2025-02-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_document_policy_claimdocument_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.customerpolicy'),
        ),
    ]
