# Generated by Django 5.1.4 on 2025-03-12 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_notification_options_notification_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('processed', 'Processed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Approval')], max_length=20),
        ),
    ]
