# Generated by Django 5.1.4 on 2025-03-12 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_premium_agent_alter_customerpolicy_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='agent',
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
